# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
      - name: Setup nNode.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run linting
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
      - name: Run unit tests
        run: npm run test
